### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by haltcase**
- Fix preset link ( copy / paste was linking to the plugin )
- Add VS Code extension
- Mention object comprehensions

### CODE REVIEW

**Comment by rattrayalex** [comment]
Awesome, thanks so much! Any chance you'd be willing to update the Sublime Text one too to indicate it's shipped?

Maybe something like this:

`Available now [on Package Control](https://packagecontrol.io/packages/LightScript)`

(if not happy to merge this and add that myself)

**Comment by haltcase** [comment]
Sure I can do that.

**Comment by rattrayalex** [comment]
thanks!

**Review by rattrayalex — APPROVED** [review]
Thanks so much!

**Pull request merged**
